version: "3"
services:
  app:
    image: "griggheo/flask-by-example:v1"
    command: "manage.py runserver --host=0.0.0.0"
    ports:
      - "5000:5000"
    environment:
      APP_SETTINGS: config.DevelopmentConfig
      DATABASE_URL: postgresql://wordcount_dbadmin:$DBPASS@db/wordcount_dev
      REDISTOGO_URL: redis://redis:6379
    depends_on:
      - db
      - redis
  worker:
    image: "griggheo/flask-by-example:v1"
    command: "worker.py"
    environment:
      APP_SETTINGS: config.DevelopmentConfig
      DATABASE_URL: postgresql://wordcount_dbadmin:$DBPASS@db/wordcount_dev
      REDISTOGO_URL: redis://redis:6379
    depends_on:
      - redis
  migrations:
    image: "griggheo/flask-by-example:v1"
    command: "manage.py db upgrade"
    environment:
      APP_SETTINGS: config.DevelopmentConfig
      DATABASE_URL: postgresql://wordcount_dbadmin:$DBPASS@db/wordcount_dev
    depends_on:
      - db
  db:
    image: "postgres:11"
    container_name: "postgres"
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
volumes:
  dbdata:
